---
services:
  fedora:
    build: .
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./tasks
          target: /tmp/tasks
          ignore:
            - todo.md
            - README.md
            - compose.yaml
            - Dockerfile
...
