---
- name: Add Hashicorp Terraform repository
  yum_repository:
    name: hashicorp
    description: Hashicorp tools repository.
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: true
  become: true

- name: Install Terraform
  dnf:
    name:
      - dnf-plugins-core
      - terraform
  become: true
 
- name: Download & unzip AWS CLI
  unarchive: 
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI & remove installer
  command: "{{ item }}"
  with_items:
    - sudo /tmp/aws/install
    - rm /tmp/aws -rf
  become: true
