---
- name: Dnf plugin core
  dnf:
    name: dnf-plugins-core
  become: true

- name: Install Docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: true

- name: Install Docker
  dnf:
    name: "{{item}}"
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin
    - docker-compose
  become: true

- name: Enabled docker service
  become: true
  service:
    name: docker
    enabled: true          
    state: started

- name: Create docker group
  group:
    name: docker
...
