---
- name: Download Cascadia nerd font
  unarchive: 
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.zip
    dest: /usr/share/fonts
    remote_src: yes

- name: Install Cascadia nerd dont
  command: fc-cache /usr/share/fonts

- name: Install terminal & shell
  dnf:
    name: 
      - fish
      - alacritty
      - wget
  become: true

- name: Install Starship prompt
  command: "{{ item }}"
  with_items:
    - wget https://starship.rs/install.sh -O /tmp/install.sh 
    - sh /tmp/install.sh -y 
    - rm /tmp/install.sh -f

- name: Install chsh command if not installed
  dnf:
    name:
      - util-linux-user
  become: true
    
- name: Change default shell
  command: chsh -s /usr/bin/fish
  become: true
...
