---
- name: Install productivity/tools packages
  become: true
  dnf:
    name:
      - tldr
      - eza
      - fzf
      - fd-find
      - ripgrep
      - screenkey
      - tmux
      - zoxide

- name: Install programming languages
  become: true
  dnf:
    name:
      - python3
      - python3-pip
      - python3-venv
      - golang
...
